# Time / framerate
TARGET_FPS = 60
MS_PER_SECOND = 1000
SECONDS_PER_MINUTE = 60

# Dimensions / layout
SURFACE_W_LG = 1000
SURFACE_H_BAR = 90
PANEL_W_MD = 480
BUTTON_Y_OFFSET = 180
FOOTER_OFFSET = 360
TITLE_FONT_SIZE = 100

WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

# Physics / units
KM_PER_MILE = 1.609344
SPEED_STEP = 0.05

# Paths
USER_DATA_DIR = "UserData/" # TODO: Fix crash when changing the path name
CARS_DIR = "/Cars/"
LEVELS_DIR = "/Levels/"
LEVEL_CODE_DIR = "/Levels/Code/"
LEVEL_MUSIC_DIR = "/Levels/Music/"
MUSIC_DIR = "Music/"
ENGINE_SFX_DIR = "engine/"
GUEST_USER = "UserData/Guest"
FONT_FILE = "font.ttf"
ICON_FONT_FILE = "icons.ttf"

# New paths

ASSETS_DIR = "game/assets"

# File extensions
EXT_WAV = ".wav"
EXT_PNG = ".png"
EXT_JPG = ".jpg"
EXT_TXT = ".txt"
DATA_BIN = "/data.bin"
CAR_PNG = "/car.png"
TEMP_CAR_PNG = "tempcar.png"

# Dictionary keys
KEY_NAME = "Name"
KEY_COLOUR = "Colour"
KEY_ANGLE = "Angle"
KEY_TYPE = "Type"
KEY_CODE = "Code"
KEY_SOUND = "Sound"
KEY_MUSIC = "Music"
KEY_ENGINE = "Engine"
KEY_SECOND = "Second"
KEY_SPEED = "Speed"

# States / screens
STATE_MAIN_MENU = "MAIN_MENU"
STATE_TITLE = "TITLE_SCREEN"
STATE_LEVEL_CREATOR = "LEVEL_CREATOR"
STATE_CAR_CREATOR = "CAR_CREATOR"
STATE_LEVEL_CREATOR_MENU = "LEVEL_CREATOR_MENU"
STATE_CAR_CREATOR_MENU = "CAR_CREATOR_MENU"
STATE_PAUSED = "PAUSED"
STATE_PAUSED_OPTIONS = "PAUSED_OPTIONS"
STATE_LEVEL_OPTIONS = "LEVEL_OPTIONS"
STATE_MENU_OPTIONS = "MENU_OPTIONS"
STATE_CREDITS = "CREDITS"
STATE_LOGIN_PAGE = "LOGIN_PAGE"

# Actions / commands
CMD_PLAY_GAME = "PLAY_GAME"
CMD_UNPAUSE = "UNPAUSE"
CMD_RESET_TIMER = "RESET_TIMER"
CMD_NEXT = "NEXT"
CMD_QUIT = "QUIT"
CMD_EDIT_LEVEL = "EDIT_LEVEL"
CMD_EDIT_CAR = "EDIT_CAR"
CMD_GET_LEVELS_DEFAULT = "GET_LEVELS_DEFAULT"
CMD_GET_LEVELS_USERNAME = "GET_LEVELS_USERNAME"
CMD_GET_CARS_DEFAULT = "GET_CARS_DEFAULT"
CMD_GET_CARS_USERNAME = "GET_CARS_USERNAME"

# Input / controls
KEY_W = "W"
KEY_A = "A"
KEY_S = "S"
KEY_D = "D"
KEY_E = "E"
DIR_UP = "Up"
DIR_DOWN = "Down"
DIR_LEFT = "Left"
DIR_RIGHT = "Right"